# Generated by Django 5.0.4 on 2024-04-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_rename_order_car_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.IntegerField(default=None),
        ),
    ]
